### ISSUE TITLE
Absolution

### ISSUE THREAD

**Issue by cg00001** [Zaxxon709/accountmanager#10]
Can you add Absolution Trakt?

**Comment by Zaxxon709** [comment]
> Can you add Absolution Trakt?

I will certianly consider adding Absolution before releasing the next update. I have an update almost ready but i still need time to complete some testing. Due to my busy schedule it will be at least a week or more before i get a chance to finish things up. Stay tuned and thanks for your suggestion and patience.

**Comment by Zaxxon709** [comment]
Absolution has been added to the latest release. If there are any issues please report them. Thanks
