### ISSUE TITLE
Seren Trakt Sync

### ISSUE THREAD

**Issue by JayDee696969** [Zaxxon709/accountmanager#6]
Can you check Seren Trakt sync? RD sync is working, but not Trakt. Thanks

**Comment by Zaxxon709** [comment]
Trakt for Seren is not supported in Account Manager. You would need to authorize Seren seperately. All supported addons are listed on github and within the addon settings menu.

I removed it due to the amount of API requests. I may look at adding it back in the next update with Custom Trakt API key support only. That means if you use your own keys it will then sync.

**Comment by casedup** [comment]
I ended up fixing the error... seems I didn't have the Metadata Providers option Enabled... Toggled it on and filled out all necessary meta accounts and working fine. Thanks for the great work!!

**Comment by Zaxxon709** [comment]
> Can you check Seren Trakt sync? RD sync is working, but not Trakt. Thanks

Seren has been added back in the latest release (v2.3.2) but with custom Trakt API support only.
